global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'prestashop-alerts@example.com'

route:
  receiver: 'email-receiver'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'admin@example.com'