groups:
  - name: prestashop_alerts
    rules:
      # Alerte si un service est down
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 30 seconds."

      # Alerte si CPU > 80%
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 2 minutes."

      # Alerte si RAM > 85%
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% for more than 2 minutes."

      # Alerte si un conteneur utilise > 500MB RAM
      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes{name=~"prestashop.*"} > 500000000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} high memory usage"
          description: "Container {{ $labels.name }} is using more than 500MB of memory."

      # Alerte si PrestaShop est inaccessible
      - alert: PrestaShopDown
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PrestaShop application is down"
          description: "PrestaShop application has been down for more than 1 minute."